In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
sent=("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.",
      "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.")

In [3]:
tfidf_vectorizer=TfidfVectorizer()
tfidf_matrix=tfidf_vectorizer.fit_transform(sent)

In [4]:
idf=tfidf_vectorizer.idf_

In [5]:
print(dict(zip(tfidf_vectorizer.get_feature_names(),idf)))

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니다': 1.0, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}


In [6]:
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
cosine_similarity(tfidf_matrix[0:1],tfidf_matrix[1:2])

array([[0.17952266]])

In [8]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[1.28099753]])

In [10]:
import numpy as np

def l1_normalize(v):
    norm=np.sum(v)
    return v/norm

tfidf_norm_l1=l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1],tfidf_norm_l1[1:2])

array([[0.20491229]])

In [14]:
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1],tfidf_norm_l1[1:2])

array([[0.77865927]])